# Generated by Django 2.0.6 on 2018-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
